const errorConstants = Object.freeze({
    INSUFFICIENT_DATA: 'INSUFFICIENT_DATA',
    NOT_AUTHENTICATED: 'NOT_AUTHENTICATED',
    EMAIL_INVALID: 'EMAIL_INVALID',
    OTP_ALREADY_SENT: 'OTP_ALREADY_SENT',
    OTP_EXPIRED: 'OTP_EXPIRED',
    OTP_NOT_SENT: 'OTP_NOT_SENT',
    OTP_NOT_MATCH: 'OTP_NOT_MATCH',
    EMAIL_PASSWORD_WRONG: 'EMAIL_PASSWORD_WRONG',
    NO_USER_FOUND: 'NO_USER_FOUND',
});
const userConstants = Object.freeze({
    ACTIVE: 'ACTIVE',
    ALREADY_ACTIVATED: 'ALREADY_ACTIVATED',
    ALREADY_REGISTERED: 'ALREADY_REGISTERED',
    DETAILS_UPDATED: 'DETAILS_UPDATED'
});
const successConstants = Object.freeze({
    OTP_ALREADY_SENT: 'OTP_ALREADY_SENT',
    OTP_SENT: 'OTP_SENT',
    REGISTRATION_RESET: 'REGISTRATION_RESET',
    REGISTERED: 'REGISTERED',
    AUTHENTICATED: 'AUTHENTICATED',
    SUCCESS: 'SUCCESS'
});


module.exports = {
    errorConstants,
    userConstants,
    successConstants
};
    